### ISSUE TITLE
You forgot something

### ISSUE THREAD

**Issue by talobin** [tkirshboim/pd-for-android#1]
`gradle assembleRelease`
You forgot to include your bash script, namely `assembleRelease`

**Comment by JesseScott** [comment]
ya!

**Comment by JesseScott** [comment]
No, wait... _assembleRelease_ isn't a file, it's a command... and if you run this in the root directory, rather than in PcCore, it works...

**Comment by tkirshboim** [comment]
Hi! Thanks for the feedback and sorry for the late reply. For some reason I didn't get a notification on this issue.
Like @JesseScott said, `assembleRelease` is a task that gradle executes. It works both in the root and in the PdCore folder for me.
@talobin - I'm not sure to which bash script you're referring to. Are you still having problems with this? If so, please explain what's not working. Or create a pull request with a fix if you like, that would be the simplest for me :smile:

**Comment by tkirshboim** [comment]
since my changes were merged to the [pd-for-android](https://github.com/libpd/pd-for-android) and it seems to work, I'm closing this here. In case you want to report other issues please do it in that repository. Thanks!
